import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Download } from "lucide-react";
import { TrendLine } from "@/components/Dashboard/TrendLine";
import { MonthlyBreakdown } from "@/components/Dashboard/MonthlyBreakdown";
import { useActivities } from "@/components/Layout/activities-store";
import {
  getTotalFootprint,
  getByCategory,
  getEcoScore,
  compareToAverage,
} from "@/utils/carbonCalc";
import { BENCHMARKS } from "@/data/emissionFactors";
import { formatNumber } from "@/utils/format";

export const Route = createFileRoute("/insights")({
  head: () => ({
    meta: [
      { title: "Insights · carbone" },
      {
        name: "description",
        content:
          "Deep dive into your monthly CO₂ trend, biggest reduction opportunities, and your eco-score.",
      },
    ],
  }),
  component: Insights,
});

const TREND = [
  { month: "Jan", kg: 520 },
  { month: "Feb", kg: 495 },
  { month: "Mar", kg: 480 },
  { month: "Apr", kg: 510 },
  { month: "May", kg: 460 },
  { month: "Jun", kg: 407 },
];

const BREAKDOWN = [
  { month: "Jan", transport: 220, energy: 170, food: 110, shopping: 20 },
  { month: "Feb", transport: 200, energy: 180, food: 100, shopping: 15 },
  { month: "Mar", transport: 195, energy: 165, food: 105, shopping: 15 },
  { month: "Apr", transport: 215, energy: 175, food: 100, shopping: 20 },
  { month: "May", transport: 180, energy: 170, food: 95, shopping: 15 },
  { month: "Jun", transport: 160, energy: 150, food: 85, shopping: 12 },
];

function Insights() {
  const { activities } = useActivities();
  const [exporting, setExporting] = useState(false);

  const { total, byCat, score, cmp, biggest } = useMemo(() => {
    const total = getTotalFootprint(activities);
    const byCat = getByCategory(activities);
    const score = getEcoScore(total);
    const cmp = compareToAverage(total);
    const biggest = (Object.entries(byCat) as [keyof typeof byCat, number][]).sort(
      (a, b) => b[1] - a[1],
    )[0];
    return { total, byCat, score, cmp, biggest };
  }, [activities]);

  async function exportPDF() {
    setExporting(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "pt", format: "a4" });
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.text("carbone — Monthly Footprint Report", 40, 60);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(110);
      doc.text(new Date().toLocaleDateString("en-IN"), 40, 80);
      doc.setTextColor(0);

      doc.setFontSize(14);
      doc.text(`Total: ${formatNumber(total)} kg CO₂  (eco-score ${score}/100)`, 40, 120);
      doc.setFontSize(11);
      doc.text(`vs India avg: ${cmp.vsIndia}%`, 40, 142);
      doc.text(`vs Global avg: ${cmp.vsGlobal}%`, 40, 158);
      doc.text(`vs Paris 2030 target: ${cmp.vsParis}%`, 40, 174);

      doc.setFontSize(14);
      doc.text("Breakdown by category", 40, 210);
      doc.setFontSize(11);
      let y = 230;
      for (const [cat, kg] of Object.entries(byCat)) {
        doc.text(`• ${cat}: ${formatNumber(kg)} kg`, 56, y);
        y += 16;
      }

      doc.setFontSize(9);
      doc.setTextColor(110);
      doc.text(
        "Factors: CEA India 0.82 kgCO2/kWh, IPCC AR6, DEFRA 2023. Generated by carbone.",
        40,
        800,
      );
      doc.save(`carbone-report-${new Date().toISOString().slice(0, 10)}.pdf`);
    } finally {
      setExporting(false);
    }
  }

  return (
    <div className="space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <p className="eyebrow">Insights</p>
          <h1 className="mt-1 font-serif text-3xl sm:text-4xl">Patterns in your footprint</h1>
          <p className="mt-1.5 text-sm text-muted-foreground">
            Where you're emitting most — and what shifting matters most.
          </p>
        </div>
        <button
          type="button"
          onClick={exportPDF}
          disabled={exporting}
          className="inline-flex min-h-11 items-center gap-2 rounded-md border-[0.5px] border-gold px-4 py-2 text-sm font-medium text-gold hover:bg-gold/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold disabled:opacity-50"
        >
          <Download className="h-4 w-4" aria-hidden="true" />
          {exporting ? "Exporting…" : "Export PDF report"}
        </button>
      </header>

      <section className="rounded-xl bg-surface p-5 hairline">
        <h2 className="mb-4 text-sm font-medium">Last 6 months</h2>
        <TrendLine data={TREND} />
      </section>

      <section className="rounded-xl bg-surface p-5 hairline">
        <h2 className="mb-4 text-sm font-medium">Monthly breakdown by category</h2>
        <MonthlyBreakdown data={BREAKDOWN} />
      </section>

      <div className="grid gap-4 md:grid-cols-3">
        <div className="rounded-xl bg-surface p-5 hairline">
          <p className="eyebrow">Peak day</p>
          <p className="mt-2 font-serif text-2xl">Thursdays</p>
          <p className="mt-1 text-sm text-muted-foreground">
            Your commute + dining out tends to spike on Thursdays.
          </p>
        </div>
        <div className="rounded-xl bg-surface p-5 hairline">
          <p className="eyebrow">Biggest opportunity</p>
          <p className="mt-2 font-serif text-2xl capitalize">{biggest?.[0] ?? "Transport"}</p>
          <p className="mt-1 text-sm text-muted-foreground">
            Cutting this by 20% saves ~{Math.round((biggest?.[1] ?? 0) * 0.2)} kg/month.
          </p>
        </div>
        <div className="rounded-xl bg-surface p-5 hairline">
          <p className="eyebrow">Eco score</p>
          <div className="mt-3 flex items-center gap-4">
            <ScoreRing score={score} />
            <div>
              <p className="font-serif text-3xl">
                {score}
                <span className="text-sm text-muted-foreground">/100</span>
              </p>
              <p className="text-xs text-muted-foreground">Beating {cmp.percentile}% of people</p>
            </div>
          </div>
        </div>
      </div>

      <section className="rounded-xl bg-surface p-5 hairline">
        <h2 className="mb-4 text-sm font-medium">How you stack up (monthly kgCO₂)</h2>
        <div className="grid grid-cols-2 gap-6 sm:grid-cols-4">
          <Stat label="You" value={Math.round(total)} highlight />
          <Stat label="India avg" value={BENCHMARKS.indiaMonthly} />
          <Stat label="Global avg" value={BENCHMARKS.globalMonthly} />
          <Stat label="Paris 2030" value={BENCHMARKS.parisMonthly} eco />
        </div>
      </section>
    </div>
  );
}

function Stat({
  label,
  value,
  highlight,
  eco,
}: {
  label: string;
  value: number;
  highlight?: boolean;
  eco?: boolean;
}) {
  return (
    <div>
      <p className="text-xs text-muted-foreground">{label}</p>
      <p
        className={`mt-1 font-serif text-3xl ${highlight ? "text-gold" : ""}`}
        style={eco ? { color: "#5a8a2a" } : undefined}
      >
        {value}
        <span className="text-sm text-muted-foreground"> kg</span>
      </p>
    </div>
  );
}

function ScoreRing({ score }: { score: number }) {
  const r = 28,
    c = 2 * Math.PI * r;
  const offset = c - (score / 100) * c;
  return (
    <svg
      width={72}
      height={72}
      viewBox="0 0 72 72"
      role="img"
      aria-label={`Eco score ${score} of 100`}
    >
      <circle cx={36} cy={36} r={r} stroke="#E8E4DC" strokeWidth="6" fill="none" />
      <circle
        cx={36}
        cy={36}
        r={r}
        stroke="#B8862A"
        strokeWidth="6"
        fill="none"
        strokeDasharray={c}
        strokeDashoffset={offset}
        strokeLinecap="round"
        transform="rotate(-90 36 36)"
      />
    </svg>
  );
}
